server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
#          uri: http://order-service:8083
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**
        - id: inventory-service
#          uri: http://inventory-service:8082
          uri: http://localhost:8082
          predicates:
            - Path=/api/inventory/**