server:
  port: 8082
spring:
  cloud:
    discovery:
      enabled: true
      service-id: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/inventory
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQLDialect
