server:
  port: 8083
spring:
  cloud:
    discovery:
      enabled: true
      service-id: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/orders
    url: jdbc:mysql://localhost:3306/orders
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
